spring:
  h2:
    console:
      enabled: true   # Context path ??
      path: /h2
  jpa:
    spring.jpa.defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test   # JDBC URL ??
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: admin@gmail.com